### ISSUE TITLE
FITS - Performance test, need Irfan's inputs on how to handle the storage.

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/drupal_fits#4]
When Fits tool generate the technical metadata, it obtain the file and store it in the tmp folder. Over time, it's accumulated and may be troublesome. Irfan suggest we put the ticket to backlog, we come back to diagnose when the problem resurfaces again.

**Comment by kylehuynh205** [comment]
Advanced queue runner can limit job(s) as a time, so this ticket is no needed anymore.
