### ISSUE TITLE
PRONOM PUID is not generated for Images

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/drupal_fits#5]
[Fits tool](https://projects.iq.harvard.edu/fits/home) doesn't generate the PRONOM PUID for Tiff and jp2. Perhaps there is a flag in the tool can be turned on to generate PRONOM PUID for these 2 image types. 

https://projects.iq.harvard.edu/fits/documentation

**Comment by amym-li** [comment]
Summarizing https://groups.google.com/g/fits-users/c/2KTgWOYmRmY/m/070-9zr-CQAJ and https://groups.google.com/g/fits-users/c/11MrhpOF1R0:
- The Droid tool is what generates the PUID values
- The Exiftool identifies the TIFF file format as TIFF EXIF whereas Droid identifies it as TIFF
- TIFF EXIF is more specific than TIFF
- Only the output of the most specific type is included in the FITS output

Solution from this response: https://groups.google.com/g/fits-users/c/11MrhpOF1R0/m/LLCn8FRXEgAJ)

>Look at the file within the the FITS deployment in xml/exiftool/exiftool_common_to_fits.xslt.
>First try commenting out lines 101 through 103 as follows and examine your resuls:
>\
>\
>\

After commenting out these lines, the Pronom PUID generates for the TIFF files as expected.

**Comment by kylehuynh205** [comment]
Tested in prod sites, and works
